from .base import Piece
import pygame as pg


class King(Piece):
    """King Piece"""
    def __init__(self, position, colour, castling_rights, *args, **kwargs):
        """Initialize the King class"""
        super().__init__(*args, *kwargs)
        self.castling_rights = castling_rights
        self.legal_directions = [(1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1), (-1, 1), (1, -1)]
        self.colour = colour
        self.position = position
        if colour == 'black':
            self.piece = 'k'
        else:
            self.piece = 'K'
        self.picture = pg.image.load(
            "data/img/pieces/" + self.piece_set + "/" + colour[0] + self.piece.lower() + ".png").convert_alpha()

    def update_legal_moves(self, board, eps, captures):
        """No-op: legal moves are generated by python-chess in Engine.update_legal_moves()."""
        self.legal_positions = []
        self.legal_captures = set()
        return

    def trim_checks(self, board, turn, map, in_check):
        """Trim legal moves based on Checks"""

        updated_moves = []
        for move in self.legal_positions:
            if (self.position[0] + move[1], self.position[1] + move[0]) not in map:
                if (move[0] == 2 or move[0] == -2) and in_check:
                    pass
                elif (move[0] == 2) and (self.position[0], self.position[1] + 1) in map:  # castle through check
                    pass
                elif (move[0] == -2) and (self.position[0], self.position[1] - 1) in map:  # castle through check
                    pass

                else:
                    updated_moves.append(move)
        self.legal_positions = updated_moves
