from .base import Piece
import pygame as pg


class Pawn(Piece):
    """Pawn Piece"""
    def __init__(self, position, colour, has_moved=False, *args, **kwargs):
        """Initialize the Pawn class"""
        super().__init__(*args, *kwargs)
        self.has_moved = has_moved
        self.colour = colour
        self.position = position
        if colour == 'black':
            self.direction = 1
            self.piece = 'p'
            self.legal_directions = [(0, 1), (0, 2)]
        else:
            self.direction = -1
            self.piece = 'P'
            self.legal_directions = [(0, -1), (0, -2)]
        self.picture = pg.image.load(
            "data/img/pieces/" + self.piece_set + "/" + colour[0] + self.piece.lower() + ".png").convert_alpha()

    def update_legal_moves(self, board, eps, captures):
        """No-op: legal moves are generated by python-chess in Engine.update_legal_moves()."""
        self.legal_positions = []
        self.legal_captures = set()
        return

    def check(self, board):
        """Can piece capture the opponents king"""
        self.checks = []
        x = self.position[1] + 1
        y = self.position[0] + self.direction
        for i in range(2):
            try:
                if board[y][x - 2 * i] != ' ' and -1 < x - 2 * i < 8:
                    if board[y][x - 2 * i].colour != self.colour and board[y][x - 2 * i].piece.lower() == 'k':
                        self.checks.append(board[y][x - 2 * i].position)
                        self.checks.append(self.position)
                        return True
            except:
                continue

        return False



