from .base import Piece
import pygame as pg

class Queen(Piece):
    """Queen Piece"""
    def __init__(self, position, colour, piece_type=None, *args, **kwargs):
        """Initialize the Queen class"""
        super().__init__(*args, *kwargs)
        self.legal_directions = [(1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1), (-1, 1), (1, -1)]
        self.colour = colour
        self.position = position
        if piece_type is not None:
            self.piece_set = piece_type
        if colour == 'black':
            self.piece = 'q'
        else:
            self.piece = 'Q'

        self.picture = pg.image.load(
            "data/img/pieces/" + self.piece_set + "/" + colour[0] + self.piece.lower() + ".png").convert_alpha()

    def update_legal_moves(self, board, eps, captures):
        """No-op: legal moves are generated by python-chess in Engine.update_legal_moves()."""
        self.legal_positions = []
        self.legal_captures = set()
        return




