from .base import Piece
import pygame as pg

class Rook(Piece):
    """Rook Piece"""
    def __init__(self, position, colour, *args, **kwargs):
        """Initialize the Rook class"""
        super().__init__(*args, *kwargs)
        self.legal_directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]
        self.colour = colour
        self.position = position

        if colour == 'black':
            self.piece = 'r'
        else:
            self.piece = 'R'
        self.picture = pg.image.load(
            "data/img/pieces/" + self.piece_set + "/" + colour[0] + self.piece.lower() + ".png").convert_alpha()

    def update_legal_moves(self, board, eps, captures):
        """No-op: legal moves are generated by python-chess in Engine.update_legal_moves()."""
        self.legal_positions = []
        self.legal_captures = set()
        return


